### ISSUE TITLE
[FEATURE] - Add unit tests for each package

### ISSUE THREAD

**Issue by ShaswatPrabhat** [callstack/reassure#201]
Right now while developing features we need to build the project every time to check against examples provided.
If we have unit tests integrated then a lot of this effort might be reduced.
Also this will ensure no existing functionality breaks during feature development.

Maybe some Jest/Mocha based scripts for unit testing which can later be evolved to check coverage and integrate with CI.

**Comment by mdjastrzebski** [comment]
Since we're using `Jest` to run perf tests, we should also use it to run our own unit test.

The reason why current code does not have tests, is that I didn't have a clear idea what meaningful tests to write that would yield enough benefit in comparison to working on other features.

My current best idea about tests to write is to prepare integration (high-level) tests for compare module, as this is the primary module that does something complex, that would feed the `compareResults` with mocked data and validate if output contains expected values.

At this stage I would avoid tests that are there just to increase the coverage, especially in other modules.

**Comment by ShaswatPrabhat** [comment]
Thinking to pick this up next, @mdjastrzebski should it be okay to do so now? Will start with some basic tests then.

**Comment by mdjastrzebski** [comment]
@ShaswatPrabhat you can experiment with tests worth adding, and we can discuss your ideas. Atm we do not have a clear scope for tests we want to add.

**Comment by mdjastrzebski** [comment]
Some tests have been added. Let's focus on adding new/missing tests tests along with regular PRs.
