### ISSUE TITLE
【Native moduels】：How to make the native modules executable by using reassure？

### ISSUE THREAD

**Issue by zhouzh1** [callstack/reassure#334]
Yeah, I must say the Reassure is really an awesome tool and I decided to use it in our app development, but I'm facing a issue that I wonder how can I make the native modules work well, because you know, by using reassure, all the react native components are rendered in the Node.js environment, but as for a commercial app in real life, it definitely depends on many native modules, so could someone help tell me that what's the best practice of processing the native modules? Thanks.

**Comment by thymikee** [comment]
Hey @zhouzh1! Thanks for using Reassure. We currently don't support rendering in the native environment. However you could use https://github.com/bamlab/android-performance-profiler to test your app's performance end-to-end and gather some metrics on Android.

**Comment by thymikee** [comment]
Closing the issue, as it's a question. But feel free to comment further :)

**Comment by mdjastrzebski** [comment]
@zhouzh1 Thanks for kind words, as @thymikee said Reassure does not support native modules as we use Jest, React Test Renderer and React Native Testing Library to run the tests. Since these tools work only in JS space, so does Reassure. Running native code requires running the app on either physicial devices and/or device simulators.

Regarding native modules you have two options:
* Mock your native modules, and use Reassure to analyse JS-side of your app performance, primarily React render performance, but also any JS computations that you have inside your components.
* Switch to another tool, [Android Performance Profiler](like https://github.com/bamlab/android-performance-profiler), if you want to analyse the app performance holistically, including both JS and native code.

Each of these solutions has it pros and cons, as well as valid use cases. A good analogy here would be integration tests (Reassure) vs end-to-end test (Android Performance Profiler), as these are the underlying technologies for both.

**Comment by zhouzh1** [comment]
@mdjastrzebski @thymikee Get it, thanks for your replies!
