### ISSUE TITLE
Make sure tests are run in-band

### ISSUE THREAD

**Issue by thymikee** [callstack/reassure#43]
Parallelizing tests create extra variance and uncertainty, making it hard to measure performance relibaly. For now, let's pass `--runInBand` option to Jest so it always run tests serially. Later on, once we have a fairly stable execution environment, we should figure out a way to parallelize tests across different CI workers (e.g. using Jest's `--shard` flag or reimplement it).

**Comment by zhouzh1** [comment]
Hi @thymikee, is Reassure able to run tests parallelly now? :)

**Comment by thymikee** [comment]
If you want to parallelize it, ideally you should run separate CI workers. You could use https://jestjs.io/docs/cli#--shard to help you do it

**Comment by mdjastrzebski** [comment]
@zhouzh1 in order to get most reliable measurements you want to run a single test at a time at a single CI machine. Therefore, if you want to run them in parallel, different tests should run on separate machines. Two test running at the same time on the same machine might interfere with each other and give false positive results.
