### ISSUE TITLE
Feature or Improvement Plans

### ISSUE THREAD

**Issue by guvenkaranfil** [callstack/reassure#445]
Is there any roadmap plan about the repository? I would like to ask about how can I contribute to repository?

**Comment by mdjastrzebski** [comment]
At the moment we are preparing for v1 release. Feature-wise it will be the same, but I plan to make some API tweaks to make it more future-proof, so that we can deliver some cool features without introducing breaking changes in v1.

If you want help, check out the issues with ["help wanted"](https://github.com/callstack/reassure/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label.

**Comment by mdjastrzebski** [comment]
Closing as not actionable.
